<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="AspNetCore.HealthChecks.Rabbitmq" />
    <PackageReference Include="AspNetCore.HealthChecks.Redis" />
    <PackageReference Include="MassTransit" />
    <PackageReference Include="MassTransit.RabbitMQ" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\BuildingBlocks\Contracts\ECommerce.Contracts.csproj" />
    <ProjectReference Include="..\..\..\BuildingBlocks\Auth\ECommerce.BuildingBlocks.Auth.csproj" />
  </ItemGroup>

</Project>
